version: "3.8"

services:
  osteoarthritis-app:
    build: .
    ports:
      - "8501:8501"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped

