name: pytorch-cuda-osteoarthritis
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - jupyterlab
  - ipywidgets
  - pillow
  - opencv
  - tqdm
  - h5py
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio
  - cudatoolkit=11.8
  - pip:
    - albumentations
    - optuna
    - tensorboard
    - plotly 